[config]
schemaVersion = "0.0.2"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Curiosity_Core_Development"
name = "SoundGate"
description = "A mod that introduces a Input Sensitivity slider to the Audio Settings, allowing players the ability to block sounds under a particular threshold." 
websiteUrl = "https://github.com/senft-research/SoundGate"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"
PEAKModding-PEAKLib_Core = "1.5.1"
PEAKModding-PEAKLib_UI = "1.5.0"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/SoundGate/release/io.senftresearch.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", ]
